<?php

class Maestrano_Connec_Model_PaymentObserver
{
    /**
     * This event is dispatched every time a payment is made
     * @param Varien_Event_Observer $observer
     */
    public function salesOrderPaymentSaveAfter(Varien_Event_Observer $observer) {
        $payment = $observer->getEvent()->getPayment();

        // Ignore payments with no sales order
        if(!$payment->getOrder()->getId()) { return; }

        // Ignore payments of type MultiplePayment as they are fake (generated by POS module)
        if($payment->getmethod() == 'MultiplePayment') { return; }

        // Refresh order to get related invoice
        $order = Mage::getModel('sales/order')->load($payment->getOrder()->getId());
        $payment->setOrder($order);

        // Process only payments linked to invoices
        if (!$order->hasInvoices() || $payment->getObserververLock() == true) {
            Mage::log('## Maestrano_Connec_Model_PaymentObserver::salesOrderPaymentSaveAfter: skipped payment '. $payment->getId());
            return;
        }

        Mage::log('## Maestrano_Connec_Model_PaymentObserver::salesOrderPaymentSaveAfter: payment ' . $payment->getId());
        
        // Process payment only if related order has been pushed to Connec!
        $mnoIdMapModel = Mage::getModel('connec/mnoidmap');
        $orderMnoIdMap = $mnoIdMapModel->findMnoIdMapByLocalIdAndEntityName($order->getId(), Mage::helper('mnomap/salesorders')->getLocalResourceName());
        if(!$orderMnoIdMap) { return; }

        // Lock the next observers for this object
        $payment->setObserververLock(true);

        /** @var Maestrano_Connec_Helper_payments $mapper */
        $mapper = Mage::helper('mnomap/payments');
        $mapper->processLocalUpdate($payment);
    }
}
